version: "3.9"

services:

  web:
    image: library/nginx:1.19.6
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/project

  php:
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    tty: "true"

  mysql:
    image: mysql:8.0.23
    ports:
      - "3316:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    env_file:
      - .env